name: vue-php-forum

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./php:/var/www/html/api

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "20100:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./vue/dist:/var/www/html/vue
      - ./php:/var/www/html/api
    depends_on:
      - php

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: forum
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db-backup.sql

  vue-build:
    image: node:22-alpine
    restart: no
    volumes:
      - ./vue:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
